#!/bin/sh

# Gradle start up script for POSIX generated by Gradle.
# This script is a placeholder. Download actual gradlew from Android Studio or gradle.org

echo "Please download the actual gradlew script from Android Studio or use 'gradle wrapper'"
